spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: http://127.0.0.1:10080/root/shoppar.git
          clone-on-start: true
      enabled: true
server:
  port: 8017
security:
  user:
    name: root
    password: 129834765
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    preferIpAddress: true